root_dir = "site"
root_url = "https://www.example.com/"
sitemap_path = "sitemap.xml"

[[rule]]
match = '\.(html|txt)$'
include = true

[[rule]]
match = '\.html$'
check_html_meta_robots = true

[[rule]]
match = '^robots\.txt$'
include = false

[[rule]]
match = '(^|/)index\.html$'
replace = '$1'

[[rule]]
match = '^secret/'
include = false
